steps:
# build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/t7-peerbook/pb', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/t7-peerbook/pb']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'pb', '--image', 'gcr.io/t7-peerbook/pb',
    '--region', 'europe-west6', '--platform', 'managed',
    '--vpc-connector', 't7'] 
images:
- gcr.io/t7-peerbook/pb
