steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/peerbook/pb', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/peerbook/pb']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'peerbook', '--image', 'gcr.io/peerbook/pb', '--region', 'europe-west6', '--platform', 'managed']
- name: 'gcr.io/cloud-builders/docker'
  args: ['-c', 'build', '-t', 'gcr.io/peerbook/pb', '.']
images:
- gcr.io/peerbook/pb
