steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/peerbook/pb', '.']
  entrypoint: 'bash'
  ENV:
    - 'PB_SMTP_HOST=email-smtp.eu-central-1.amazonaws.com'
    - 'PB_STATIC_ROOT=/app/html'
  secretEnv: ['PB_SMTP_USER', 'PB_SMTP_PASS']
availableSecrets:
  secretManager:
  - versionName: projects/peerbook/secrets/smtp-user/versions/latest
    env: PB_SMTP_USER
  - versionName: projects/peerbook/secrets/smtp-pass/versions/latest
    env: PB_SMTP_PASS

