version: '3'
services:
  api:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/peerbook/server:${VERSION}
    hostname: api
    ports:
      - "17777"
    environment:
      AWS_REGION: ${AWS_REGION}
    logging:
      driver: awslogs
      options:
        awslogs-group: api
        awslogs-region: ${AWS_REGION}