# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://github.com

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build and push
        env: # Or as an environment variable
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}    
          AWS_REGION: ${{ secrets.AWS_REGION }}      
        run: |
          cd $GITHUB_WORKSPACE
          bash deployment/build_and_push.sh


      # Runs a set of commands using the runners shell
      - name: deploy
        env: # Or as an environment variable
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}    
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}    
          AWS_REGION: ${{ secrets.AWS_REGION }} 
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          TARGET_GROUP_ID: ${{ secrets.API_TARGET_GROUP_ID }}
        run: bash deployment/deploy.sh
