name: deploy-staging

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://github.com


    steps:
      # install ecs-cli
      - name: install ecs-cli
        run: |
          sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
          sudo chmod +x /usr/local/bin/ecs-cli

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: build and push
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}    
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} 
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: |
          cd $GITHUB_WORKSPACE
          bash deployment/build_and_push.sh



      - name: deploy
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}    
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}    
          AWS_REGION: ${{ secrets.AWS_REGION }} 
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          TARGET_GROUP_ID: ${{ secrets.API_TARGET_GROUP_ID }}
        run: |
          cd deployment
          bash deploy.sh       
